import fs from "fs";
import path from "path";
import crypto from "crypto";

console.log("==================================================================");
console.log("   OBSIDIAN CAD PREVIEW - PLUGIN & JAVASCRIPT TEST SUITE         ");
console.log("==================================================================\n");

let passed = 0;
let failed = 0;

function assert(condition, name, extra = "") {
    if (condition) {
        passed++;
        console.log(`  \x1b[32m[PASS]\x1b[0m ${name} ${extra ? `(${extra})` : ""}`);
    } else {
        failed++;
        console.log(`  \x1b[31m[FAIL]\x1b[0m ${name} ${extra ? `-> ${extra}` : ""}`);
    }
}

// 1. Manifest & Plugin Package Tests
console.log("[1] MANIFEST & PACKAGE CONFIGURATION");
const manifestPath = path.join(process.cwd(), "manifest.json");
assert(fs.existsSync(manifestPath), "manifest.json exists");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
assert(manifest.id === "obsidian-cad-preview", "Plugin ID matches 'obsidian-cad-preview'");
assert(manifest.isDesktopOnly === true, "Plugin marked as isDesktopOnly for CAD Bridge");

const packagePath = path.join(process.cwd(), "package.json");
assert(fs.existsSync(packagePath), "package.json exists");
const pkg = JSON.parse(fs.readFileSync(packagePath, "utf-8"));
assert(pkg.dependencies.three !== undefined, "Three.js is declared in dependencies");

// 2. Build Artifacts
console.log("\n[2] BUILD ARTIFACTS INTEGRITY");
const mainJsPath = path.join(process.cwd(), "main.js");
assert(fs.existsSync(mainJsPath), "main.js is generated by esbuild");
const mainJsStat = fs.statSync(mainJsPath);
assert(mainJsStat.size > 500000, "main.js bundles Three.js and modules", `${(mainJsStat.size / 1024).toFixed(0)} KB`);

const stylesCssPath = path.join(process.cwd(), "styles.css");
assert(fs.existsSync(stylesCssPath), "styles.css exists");
const styles = fs.readFileSync(stylesCssPath, "utf-8");
assert(styles.includes(".obsidian-cad-container"), "styles.css contains CAD container class");
assert(styles.includes(".cad-tree-node"), "styles.css contains Assembly Tree styles");
assert(styles.includes(".cad-tool-overlay"), "styles.css contains Sectioning & Measurement styles");

// 3. Link Parsing & Syntactic Regex Tests (Section 5, 6)
console.log("\n[3] EMBED LINK SYNTAX PARSER TESTS");
function parseEmbedSource(rawSrc) {
    const supported = [".prt", ".step", ".stp", ".jt"];
    const parts = rawSrc.split("|");
    const filePath = parts[0].trim();
    const ext = path.extname(filePath).toLowerCase();

    if (!supported.includes(ext)) {
        return { isCad: false, filePath, options: {} };
    }

    let alias;
    const options = {};

    for (let i = 1; i < parts.length; i++) {
        const param = parts[i].trim();
        if (param.includes("=")) {
            const [key, val] = param.split("=").map(s => s.trim());
            if (key.toLowerCase() === "height" && !isNaN(parseInt(val, 10))) {
                options.height = parseInt(val, 10);
            } else if (key.toLowerCase() === "width") {
                options.width = val;
            } else if (key.toLowerCase() === "quality") {
                options.quality = val;
            } else if (key.toLowerCase() === "camera" || key.toLowerCase() === "projection") {
                options.projection = val;
            }
        } else if (!alias) {
            alias = param;
        }
    }

    return { isCad: true, filePath, alias, options };
}

const testCase1 = parseEmbedSource("Housing.prt");
assert(testCase1.isCad && testCase1.filePath === "Housing.prt", "Parses simple ![[Housing.prt]]");

const testCase2 = parseEmbedSource("Models/Assembly.prt|Редуктор");
assert(testCase2.isCad && testCase2.alias === "Редуктор", "Parses alias ![[Models/Assembly.prt|Редуктор]]");

const testCase3 = parseEmbedSource("Assembly.prt|width=100%|height=500|quality=high");
assert(testCase3.isCad && testCase3.options.height === 500 && testCase3.options.width === "100%" && testCase3.options.quality === "high", "Parses display options ![[Assembly.prt|width=100%|height=500|quality=high]]");

const testCase4 = parseEmbedSource("Drawing.pdf");
assert(!testCase4.isCad, "Ignores non-CAD files (![[Drawing.pdf]])");

// 4. SHA-256 Cache Key Determinism Tests (Section 34)
console.log("\n[4] SHA-256 CACHE DETERMINISM");
function generateCacheKey(absolutePath, size, mtime, quality = "normal") {
    const normalized = path.normalize(absolutePath).toLowerCase();
    const converterVersion = 1;
    const payload = `${normalized}|${size}|${mtime}|${converterVersion}|${quality}`;
    return crypto.createHash("sha256").update(payload).digest("hex").slice(0, 16);
}

const key1 = generateCacheKey("D:/Vault/Models/Assembly.prt", 10240, 1786643233, "normal");
const key2 = generateCacheKey("d:\\vault\\models\\assembly.prt", 10240, 1786643233, "normal");
assert(key1 === key2, "Cache key is path-casing and slash normalized", key1);

const key3 = generateCacheKey("D:/Vault/Models/Assembly.prt", 10241, 1786643233, "normal");
assert(key1 !== key3, "Changing file size invalidates cache key");

const key4 = generateCacheKey("D:/Vault/Models/Assembly.prt", 10240, 1786643233, "high");
assert(key1 !== key4, "Changing quality setting invalidates cache key");

console.log("\n==================================================================");
console.log(`   PLUGIN TEST RESULTS: ${passed} PASSED | ${failed} FAILED`);
console.log("==================================================================");

process.exit(failed === 0 ? 0 : 1);
